"""brand_hierarchy

Revision ID: b2c3d4e5f6a1
Revises: a1b2c3d4e5f6
Create Date: 2026-06-15 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b2c3d4e5f6a1"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE product_brands ADD COLUMN IF NOT EXISTS tier VARCHAR(20);")
    op.execute("ALTER TABLE product_brands ADD COLUMN IF NOT EXISTS brand_type VARCHAR(30);")
    op.execute("ALTER TABLE product_brands ADD COLUMN IF NOT EXISTS website VARCHAR(255);")
    op.execute("ALTER TABLE product_brands ADD COLUMN IF NOT EXISTS notes TEXT;")
    op.execute("ALTER TABLE product_brands ADD COLUMN IF NOT EXISTS logo_url VARCHAR(512);")
    op.execute(
        """
        CREATE TABLE importers (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name VARCHAR(120) NOT NULL UNIQUE,
            short_name VARCHAR(120),
            website VARCHAR(255),
            hq_state VARCHAR(50),
            notes TEXT,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
        );
        """
    )
    op.execute(
        """
        CREATE TABLE manufacturers (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name VARCHAR(120) NOT NULL UNIQUE,
            country VARCHAR(80) NOT NULL DEFAULT 'China',
            website VARCHAR(255),
            notes TEXT,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
        );
        """
    )
    op.execute(
        """
        CREATE TABLE brand_importers (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            brand_id INTEGER NOT NULL REFERENCES product_brands(id) ON DELETE CASCADE,
            importer_id INTEGER NOT NULL REFERENCES importers(id) ON DELETE CASCADE,
            relationship_type VARCHAR(30) NOT NULL DEFAULT 'carries',
            notes TEXT,
            UNIQUE (brand_id, importer_id)
        );
        """
    )
    op.execute(
        """
        CREATE TABLE brand_manufacturers (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            brand_id INTEGER NOT NULL REFERENCES product_brands(id) ON DELETE CASCADE,
            manufacturer_id INTEGER NOT NULL REFERENCES manufacturers(id) ON DELETE CASCADE,
            notes TEXT,
            UNIQUE (brand_id, manufacturer_id)
        );
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS brand_manufacturers;")
    op.execute("DROP TABLE IF EXISTS brand_importers;")
    op.execute("DROP TABLE IF EXISTS manufacturers;")
    op.execute("DROP TABLE IF EXISTS importers;")
    op.execute("ALTER TABLE product_brands DROP COLUMN IF EXISTS logo_url;")
    op.execute("ALTER TABLE product_brands DROP COLUMN IF EXISTS notes;")
    op.execute("ALTER TABLE product_brands DROP COLUMN IF EXISTS website;")
    op.execute("ALTER TABLE product_brands DROP COLUMN IF EXISTS brand_type;")
    op.execute("ALTER TABLE product_brands DROP COLUMN IF EXISTS tier;")
