"""store_documents

Revision ID: e5f6a1b2c3d4
Revises: d4e5f6a1b2c3
Create Date: 2026-06-15 00:00:00.000000
"""

from typing import Sequence, Union

from alembic import op


revision: str = "e5f6a1b2c3d4"
down_revision: Union[str, None] = "d4e5f6a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS store_documents (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name VARCHAR(255) NOT NULL,
            category VARCHAR(60) NOT NULL DEFAULT 'Other',
            file_path VARCHAR(512) NOT NULL,
            file_size INTEGER,
            mime_type VARCHAR(100),
            notes TEXT,
            uploaded_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
            supplier_name VARCHAR(120),
            doc_date VARCHAR(20)
        );
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS store_documents;")
